"""
Project Euler Problem 75
========================

It turns out that 12 cm is the smallest length of wire can be bent to form
a right angle triangle in exactly one way, but there are many more
examples.

12 cm: (3,4,5)
24 cm: (6,8,10)
30 cm: (5,12,13)
36 cm: (9,12,15)
40 cm: (8,15,17)
48 cm: (12,16,20)

In contrast, some lengths of wire, like 20 cm, cannot be bent to form a
right angle triangle, and other lengths allow more than one solution to be
found; for example, using 120 cm it is possible to form exactly three
different right angle triangles.

120 cm: (30,40,50), (20,48,52), (24,45,51)

Given that L is the length of the wire, for how many values of L 1,500,000
can exactly one right angle triangle be formed?
"""

# approach a) parametrize pitagorian triplets using Euclid's formula: 
# every pitagorian triplet can be generated by: u^2 - v^2, 2uv, u^2 + v^2 where u>v, gcd(u,v)=1 and at least one u,v are even.
# this will generaate all 


import math

# this finds all integer pitagorian triplets a,b,c where a+b+c <= upper_limit 

# every primitive pitagorian triplet can be generated by:
# (a,b,c) = (u^2 - v^2)/2, uv, (u^2 + v^2)/2 where u>v, gcd(u,v)=1 and both u,v are odd.
# from there, multiplying by a constant generates until less than perimiter lenght generates all numbers
# see variant approach here: https://en.wikipedia.org/wiki/Pythagorean_triple 

upper_limit = 1500000

def calculate_all_triplets(upper_limit):

    triples = []
    for u in range(1, math.isqrt(upper_limit) + 1, 2):
        for v in range(1, u, 2):
            if math.gcd(u, v) == 1:
                a = (u**2 - v**2)//2
                b = u*v
                c = (u**2 + v**2)//2
                for i in range(1, (upper_limit//(a+b+c)) + 1) :
                    triples.append((i*a, i*b, i*c))
    return list(triples)




triples = calculate_all_triplets(upper_limit)
perim_cont = [0]*upper_limit   # count how many triplets there are for a specific perimeter 

for triplet in triples:
    perim_cont[sum(triplet)-1] += 1

print(sum([1 for x in perim_cont if x == 1]))
